### ISSUE TITLE
Any suggestion or instruction to follow, step by step?

### ISSUE THREAD

**Issue by sameul2012** [dmfxyz/foundry-docker-tutorial#1]
Is it possible to give some specific steps to follow?
How to utilize this repository?

**Comment by dmfxyz** [comment]
Please see the Readme! There is a link to a chapter in the foundry book that provides examples / a walkthrough

**Comment by sameul2012** [comment]
Are you meaning, 'https://book.getfoundry.sh/tutorials/foundry-docker.html' ?

I think, that link point to this repo, and this repo point to that link....

![image](https://user-images.githubusercontent.com/106046511/174934317-cb760c33-b65e-4c59-a1e1-4b146a251c57.png)
