### ISSUE TITLE
how to solve this alarm of import error?

### ISSUE THREAD

**Issue by sameul2012** [dmfxyz/foundry-docker-tutorial#2]
after git clone this repository, I got below alarm, how to solve it?

![image](https://user-images.githubusercontent.com/106046511/174921620-1cbc512f-21a0-4a4e-b21f-566a25b1f863.png)

```bash
$ docker run -v $PWD:/app foundry "forge test --root /app --watch"
```

Unable to resolve import: "solmate/tokens/ERC721.sol" with remappings:
        ds-test/=/app/lib/ds-test/src/
        src/=/app/src/
Unable to resolve import: "openzeppelin-contracts/contracts/utils/Strings.sol" with remappings:
        ds-test/=/app/lib/ds-test/src/
        src/=/app/src/
Unable to resolve import: "openzeppelin-contracts/contracts/access/Ownable.sol" with remappings:
        ds-test/=/app/lib/ds-test/src/
        src/=/app/src/
Error: 
   0: Failed to resolve file: "/app/lib/ds-test/src/test.sol": No such file or directory (os error 2).
       Check configured remappings.

Location:
   cli/src/compile.rs:99

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by dmfxyz** [comment]
did you clone the submodules in the `lib` folder by either running `forge install` or `git submodule update --init`?

**Comment by sameul2012** [comment]
cool, that's great. `git submodule update --init` helped.

![image](https://user-images.githubusercontent.com/106046511/174926275-94527d20-ec93-4d01-b01c-b0e436000d8b.png)

But, where to run `forge install`, enter the container?
I tried this way, got below result.

![image](https://user-images.githubusercontent.com/106046511/174927034-d7f6ebf0-d3e4-4283-8de8-668913f4ec64.png)

**Comment by sameul2012** [comment]
Also, I tried the host directory of lib,

![image](https://user-images.githubusercontent.com/106046511/174927410-4748a9f7-f475-4826-a780-1a4db6e826e8.png)

It obviously should not work, coz, I did not install foundry locally...

**Comment by dmfxyz** [comment]
Without local foundry then you did the correct thing with `git submodule`
