### ISSUE TITLE
where code is located in the container

### ISSUE THREAD

**Issue by sameul2012** [dmfxyz/foundry-docker-tutorial#3]
As the doc said, 

https://book.getfoundry.sh/tutorials/foundry-docker.html

`You can see our code was compiled and tested entirely within the container. Also, since we passed the --watch option, the container will recompile the code whenever a change is detected.`

Where the make the change, where code located in the container?

![image](https://user-images.githubusercontent.com/106046511/174934725-efe8a41a-5766-4b56-a6a3-91501f7d0db7.png)

**Comment by dmfxyz** [comment]
Again, this is covered in the tutorial. You make the change on your host file system because you are mounting the files into the container.
