### ISSUE TITLE
No such file or directory (os error 2)?

### ISSUE THREAD

**Issue by sameul2012** [dmfxyz/foundry-docker-tutorial#4]
Why cannot forge init proj in the container?

![image](https://user-images.githubusercontent.com/106046511/174972882-b279ece5-8e28-4af9-affa-3d6e647f6fb5.png)

per the doc of https://book.getfoundry.sh/projects/creating-a-new-project.html

This creates a new directory hello_foundry from the default template. This also initializes a new git repository.

**Comment by dmfxyz** [comment]
Closed because it's covered in the Docker Section of the book. (https://book.getfoundry.sh/tutorials/foundry-docker.html)
